#!/bin/bash

echo "-----------------------------------------------------------------------------------------------------"
echo "| Feature                  | Action                                | Key/Command                  |"
echo "-----------------------------------------------------------------------------------------------------"
echo "| **Searching Through Page**                                                                           |"
echo "| Search for a term        | Type /term and press Enter            | /                            |"
echo "| Navigate to next match   | Go to next match                      | n                            |"
echo "| Navigate to prev match   | Go to previous match                  | N                            |"
echo "| Highlight all matches    | Highlight search results              | :set hlsearch               |"
echo "| Clear highlights         | Remove search highlights              | :noh                        |"
echo "-----------------------------------------------------------------------------------------------------"
echo "| **Selecting Text**                                                                                  |"
echo "| Enter visual mode        | Select text by characters             | v (normal mode)              |"
echo "| Select entire line       | Highlight the whole line              | V                            |"
echo "| Visual block mode        | Select block of text                  | Ctrl+v                       |"
echo "| Search and select        | Search for term and select matches    | /term + v                    |"
echo "-----------------------------------------------------------------------------------------------------"
echo "| **Cutting and Deleting Text**                                                                       |"
echo "| Cut current line         | Delete the current line               | dd                           |"
echo "| Cut to end of line       | Delete from cursor to end of line     | d$                           |"
echo "| Cut to end of file       | Delete from cursor to file end        | dG                           |"
echo "| Copy current line        | Yank the current line                 | yy                           |"
echo "| Copy to end of line      | Yank from cursor to end of line       | y$                           |"
echo "| Paste after cursor       | Paste copied/cut text after cursor    | p                            |"
echo "| Paste before cursor      | Paste copied/cut text before cursor   | P                            |"
echo "-----------------------------------------------------------------------------------------------------"
echo "| **Undo and Redo**                                                                                   |"
echo "| Undo last change         | Undo the last change                  | u                            |"
echo "| Undo changes to line     | Undo all changes on selected line     | U                            |"
echo "| Redo last undone change  | Redo the previous undone action       | Ctrl+r                       |"
echo "-----------------------------------------------------------------------------------------------------"
echo "| **Manipulating Text**                                                                               |"
echo "| Indent right             | Indent the current line to the right  | >>                           |"
echo "| Indent left              | Indent the current line to the left   | <<                           |"
echo "| Indent multiple lines    | Indent selected lines                 | > or < (visual mode)         |"
echo "| Move text                | Select and move text                  | Visual + :m + range          |"
echo "| Replace character        | Replace character under cursor        | r<char>                      |"
echo "| Enter replace mode       | Replace multiple characters           | R                            |"
echo "| Change entire line       | Delete and start editing a line       | cc                           |"
echo "| Change a word            | Change word under cursor              | cw                           |"
echo "| Change to end of line    | Change from cursor to end of line     | c$                           |"
echo "| Duplicate line           | Copy and paste the current line       | yyp                          |"
echo "-----------------------------------------------------------------------------------------------------"
echo "| **Advanced Features in NvChad**                                                                     |"
echo "| File search              | Search files with Telescope           | <leader>ff                   |"
echo "| Search in files          | Live grep with Telescope              | <leader>fg                   |"
echo "| Syntax-aware highlights  | Use Tree-Sitter for better selections | Enabled by default           |"
echo "| Code actions             | Show code actions (LSP)               | <leader>ca                   |"
echo "| Rename variable          | Rename variables in LSP               | <leader>rn                   |"
echo "-----------------------------------------------------------------------------------------------------"

echo "| Syntax-aware highlights  | Use Tree-Sitter for better selections | Enabled by default           |"
echo "| Code actions             | Show code actions (LSP)               | <leader>ca                   |"
echo "| Rename variable          | Rename variables in LSP               | <leader>rn                   |"
echo "-----------------------------------------------------------------------------------------------------"




echo "-----------------------------------------------------------------------------------------------------"
echo "| Syntax-aware highlights  | Use Tree-Sitter for better selections | Enabled by default           |"
echo "| Code actions             | Show code actions (LSP)               | <leader>ca                   |"
echo "| Rename variable          | Rename variables in LSP               | <leader>rn                   |"
echo "-----------------------------------------------------------------------------------------------------"
echo ""
echo "Keyboard shortcuts"
echo ""
echo "    space + v: Opens a vertical terminal"
echo "    space + h: Opens a horizontal terminal"
echo "    alt + v: Toggles a vertical terminal on or off"
echo "    alt + h: Toggles a horizontal terminal on or off"
echo ""
echo "Toggleterm.nvim plugin"
echo ""
echo "    ToggleTermToggleAll: Opens or closes all previously toggled terminals"
echo ""
echo "Floating terminal functionality: Allows you to open a terminal in a floating window"
echo ""
echo "Other commands"
echo ""
echo "    <leader> + H: Opens a new terminal"
echo "    <leader> + J: Enables an existing terminal"
echo "    <leader> + K: Hides a terminal"
echo "    <leader>x: Hides the terminal window without deleting the buffer"
echo "    bd!: Closes the terminal buffer"
